= Ansible Modules

This repository contains some Ansible modules that I wrote earlier.

If you like some module and you want to merge it into the upstream, then feel free to do it.
But please, do not make me involved.
I was contributing to Ansible earlier, but not anymore.


== List of Modules

link:library/system/eselect.py[eselect]::
  Module for Gentoo’s multi-purpose configuration and management tool eselect.

link:library/database/ldap.py[ldap]::
  This module adds, modifies and removes entries in LDAP server, similarly as `ldapmodify` command.

link:library/files/mktemp_dir[mktemp_dir]::
  Very simple module that creates a temporary directory on the remote server and returns its path.

link:library/database/mongodb_replset.py[mongodb_replset]::
  This module allows to initiate a new replica set or add new members to an existing one.
  It can’t remove members from a replica set, this should be always done with caution by hand.

link:library/packaging/mvn_get.py[mvn_get]::
  Downloads artifacts from Maven repository.
  Resolves version of the artifact, but does _not_ resolve its dependencies.
  It’s intended just for fetching single artifact from repository, nothing more.

link:library/database/postgresql_exec.py[postgresql_exec]::
  This module is intended for initializing database schema and maybe populating with some seed data from a SQL script.
  However, it can be used to execute any SQL commands.
  It is up to the user to maintain idempotence.


== License

All modules are licensed under https://www.gnu.org/copyleft/gpl-3.0.html[GPLv3].
For the full text of the license, see the link:LICENSE[LICENSE] file.
